export const WordsTechnoBabbleProNouns: string[] = [
    "Tritanium",
    "Lexorian",
    "Magnesite-nitron",
    "Infernite",
    "Autoemulator",
    "Verterium",
    "Cortenide",
    "Tritanium",
    "Argine",
    "Toranium",
    "Magnaspanner",
    "Encabulator",
    "Conductor",
    "Drive",
    "Wayne Shaft",
    "Manifold", 
    "Resistor", 
    "Amplifier", 
    "Canister", 
    "Capacitor", 
    "Coil", 
    "Circut", 
    "Conduit", 
    "Core", 
    "Driver", 
    "Injector", 
    "Oscillator",
    "Processor",
    "Stabiliser",
    "RM-Motor",
    "Matrix",
    "Resonator"

];

export const WordsTechnoBabbleDescription: string[] = [
    "Acidic",
    "Turbo",
    "Magneto-Reluctance",
    "Continuously Variable",
    "Stable",
    "Light Emitting",
    "Electronic",
    "Gauss",
    "Rigid",
    "Plug-in",
    "Animatronic",
    "Bleeding Edge",
    "Cybernetic",
    "Fifth-generation",
    "Mobile",
    "Native",
    "Redundant",
    "Dielectric",
    "Potted",
    "Electrolydic",
    "Thin film",
    "Analog", 
    "Asynchronous", 
    "Real-time", 
    "Nested", 
    "RS-232", 
    "Augmented", 
    "Auxiliary", 
    "Artificial", 
    "Harmonic", 
    "Insulated", 
    "Magnetic", 
    "Modulated", 
    "Primary", 
    "Secondary", 
    "Backup", 
    "Control", 
    "Optical",
    "Recalibrated",
    "Spectral",
    "Wide-band",
    "Dynamic",
    "Parallel",
    
];

export const WordsCar: string[] = [
    "Antilock Braking System",
    "Adaptive Cruise Control",
    "Autonomous Emergency Braking",
    "All-Wheel Drive",
    "Brake Horsepower",
    "Continuously Variable Transmission",
    "Direct Diesel Injection",
    "Direct Fuel Injection",
    "Diesel Particulate Filter",
    "Daytime Running Lights",
    "Dynamic Stability Control",
    "Direct-Shift Gearbox",
    "Extended-Range Electric Vehicle",
    "Electronic Stability Control",
    "Electronic Stability Program",
    "Electric Vehicle",
    "Front Wheel Drive",
    "Global Positioning System",
    "Hybrid Vehicle",
    "ISOFIX",
    "Lane Departure Warning System",
    "Light Emitting Diode",
    "Limited Slip Differential",
    "Liquid Petroleum Gas",
    "Long Wheelbase",
    "Plug-in Hybrid Electric Vehicle",
    "Revolutions Per Minute",
    "Rear Wheel Drive",
    "Sports Utility Vehicle",
    "Traction Control System",
    "Thin Film Transistor",
    "Vehicle Identification Number",
    "C-pillar",
    "Brake Horsepower",
    "Gearbox",
    "Crankcase",
    "Direct Diesel Injection",
    "Dampers",
    "Differential",
    "Double Overhead Camshaft",
    "Diesel Particulate Filter",
    "Dry weight",
    "Dynamic Stability Control",
    "Direct-Shift Gearbox",
    "Dual Fuel",
    "Extended-Range Electric Vehicle",
    "E-REV",
    "Full Dealer Service History",
    "Flexible Fuel Vehicles",
    "HPI Check",
    "Hybrid",
    "Internal Combustion Engine vehicle",
    "Independent suspension",
    "i-VTEC",
    "Intelligent Variable Valve Timing and Lift Electronic Control",
    "Intercooler",
    "J-turn",
    "Kerb weight",
    "Leaf-spring suspension",
    "Light Emitting Diode",
    "Limited Slip Differential",
    "Liquid Petroleum Gas",
    "Long Wheelbase",
    "MacPherson Strut",
    "Marque",
    "Monocoque chassis",
    "Multi-link suspension",
    "Naturally aspirated",
    "Notchback",
    "Octane",
    "Odometer",
    "OTR",
    "Oversteer",
    "Petrol engine",
    "PHEV",
    "Pillars",
    "Platform",
    "Power Steering",
    "PS",
    "Privacy Glass",
    "Q Plate",
    "Range Anxiety",
    "Regenerative Braking",
    "Ringer",
    "Road Tax Band",
    "Rear Wheel Drive",
    "Satellite Navigation",
    "Sat Nav",
    "Segment",
    "Supercharger",
    "TCS",
    "TFT",
    "Torque",
    "Torque steer",
    "Torsional rigidity",
    "Transmission",
    "Trim level",
    "Turbocharger",
    "Understeer",
    "Valves",
    "Vehicle platform",
    "VIN",
    "VRM",
    "Wankel engine",
    "Wheelbase",
    "Xenon",
    "Yugo",
    "ZiL lanes"
];

export const WordsComputer: string[] = [
    "Disk",
    "Data",
    "Bit",
    "Nybble",
    "Byte",
    "Kilobyte",
    "Megabyte",
    "Gigabyte",
    "Terabyte",
    "Petabyte",
    "Upload",
    "Download",
    "Load",
    "Save",
    "RAM",
    "ROM",
    "Hardware",
    "CPU",
    "GHz",
    "USB",
    "Email",
    "World Wide Web",
    "Broadband",
    "WiFi",
    "Plug & Play",
    "OS",
    "Program",
    "Software",
    "Installation",
    "Computer Virus",
    "Hacker",
    "Acrobat",
    "Adware",
    "Aliasing",
    "Appletalk",
    "Applications",
    "ATX",
    "AVI",
    "Bad Sector",
    "Bad Block",
    "Beta Software",
    "BIOS",
    "Broadband",
    "Brown Out",
    "Brower",
    "Cache",
    "Complimentary Metal Oxide Semi-conductor",
    "Category 6",
    "Category 5",
    "DHTML",
    "Domain name",
    "Delegate",
    "DHTML",
    "Domain Delegation",
    "Dongle"
]

export const Templates: string[] = [
    "The {{{thing}}} sounds like its broken.",
    "The {{{thing}}} sounds like its broken, it might also be the {{{also}}}.",
    "The {{{thing}}} which runs the {{{thing}}} has interacted with the {{{thing}}} causing a failure in the {{{also}}}",
    "The {{{thing}}} has interacted with the {{{thing}}} causing a failure in the {{{also}}}",
    "The {{{thing}}} has interacted with the {{{also}}}",
    "The {{{thing}}} has interacted with the {{{thing}}}",
    "The {{{thing}}} has unlatched with the {{{thing}}}",
]

export const Starters: string[] = [
    "Due to your behavior, ",
    "Due to your actions, ",
    "From your answers, ",
    "Having calculated your results, "
]